# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a8426848665a45c83c13647b98cc82607ae435afcf1fb764a6f9fd575a944de60529e830140c50ea73ce43d4aaf89599fd1dcd224dd3146721184cd63d8aaea

test:
  secret_key_base: 7dde1ab62e0ed707cf5aa258860cbbbc08b21988bd3f090c113be24412130dcaa880fc6f59f13644ca9afb657aa0aa90a1e3620ccb7ac94189761e2e0c9f303e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
